"""Relational snapshot schema; JSON is limited to small numerical/identity metadata."""

from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    Float,
    ForeignKey,
    Integer,
    MetaData,
    String,
    Table,
    UniqueConstraint,
)

metadata = MetaData()
analyses = Table(
    "analyses",
    metadata,
    Column("analysis_id", String, primary_key=True),
    Column("created_at", String, nullable=False, index=True),
    Column("analysis_type", String, nullable=False, index=True),
    Column("recipe_id", String, nullable=False, index=True),
    Column("recipe_name", String, nullable=False),
    Column("recipe_version", String, nullable=False),
    Column("equivalent_q", Float),
    Column("target_q", Float),
    Column("d_min", Float, nullable=False),
    Column("d_max", Float, nullable=False),
    Column("interpolation_method", String, nullable=False),
    Column("packing_model", String, nullable=False),
    Column("sse", Float),
    Column("rmse", Float),
    Column("mae", Float),
    Column("max_absolute_deviation", Float),
    Column("fit_status", String, nullable=False),
    Column("comparison_metadata", JSON),
    Column("convention_key", String, nullable=False),
)
snapshots = Table(
    "analysis_snapshots",
    metadata,
    Column("snapshot_id", String, primary_key=True),
    Column("analysis_id", ForeignKey("analyses.analysis_id", ondelete="CASCADE"), nullable=False),
    Column("role", String, nullable=False),
    Column("profile", JSON, nullable=False),
    Column("fit", JSON, nullable=False),
    Column("curve_bases", JSON, nullable=False),
    Column("input_fraction_sum", Float, nullable=False),
    Column("algorithm_version", String, nullable=False),
    Column("is_simulation", Boolean, nullable=False),
    Column("recipe_id", String),
    Column("recipe_name", String),
    Column("recipe_version", String),
    Column("recipe_status", String),
    Column("approval_reference", String),
    UniqueConstraint("analysis_id", "role"),
)
materials = Table(
    "analysis_materials",
    metadata,
    Column(
        "snapshot_id",
        ForeignKey("analysis_snapshots.snapshot_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("position", Integer, primary_key=True),
    Column("line_id", String, nullable=False),
    Column("material_id", String, nullable=False),
    Column("batch_id", String, nullable=False),
    Column("batch_no", String, nullable=False, index=True),
    Column("supplier", String, nullable=False),
    Column("density_kg_m3", Float),
    Column("density_kind", String),
    Column("mass_fraction", Float, nullable=False),
    Column("actual_weight", Float),
    Column("uniform_density_confirmed", Boolean, nullable=False),
    Column("psd_id", String, nullable=False),
    Column("measurement_version", String, nullable=False),
    Column("method", String, nullable=False),
    Column("protocol_id", String, nullable=False),
    Column("source_hash", String, nullable=False),
    Column("basis", String, nullable=False),
    Column("lower_tail_confirmed", Boolean, nullable=False),
    Column("upper_tail_confirmed", Boolean, nullable=False),
)
points = Table(
    "analysis_psd_points",
    metadata,
    Column(
        "snapshot_id",
        ForeignKey("analysis_snapshots.snapshot_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("curve", String, primary_key=True),
    Column("position", Integer, primary_key=True),
    Column("particle_size", Float, nullable=False),
    Column("passing", Float),
)
keys = Table(
    "analysis_key_sizes",
    metadata,
    Column("role", String, primary_key=True),
    Column(
        "snapshot_id",
        ForeignKey("analysis_snapshots.snapshot_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("position", Integer, primary_key=True),
    Column("particle_size", Float, nullable=False),
    Column("passing", Float),
    Column("reason", String),
)
recipe_lines = Table(
    "analysis_recipe_lines",
    metadata,
    Column(
        "snapshot_id",
        ForeignKey("analysis_snapshots.snapshot_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("position", Integer, primary_key=True),
    Column("line_id", String, nullable=False),
    Column("material_id", String, nullable=False),
    Column("mass_fraction", Float, nullable=False),
    Column("allowed_material_ids", JSON, nullable=False),
)
metrics = Table(
    "analysis_metrics",
    metadata,
    Column(
        "snapshot_id",
        ForeignKey("analysis_snapshots.snapshot_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("role", String, primary_key=True),
    Column("sse", Float, nullable=False),
    Column("rmse", Float, nullable=False),
    Column("mae", Float, nullable=False),
    Column("max_absolute_deviation", Float, nullable=False),
    Column("n", Integer, nullable=False),
)
diagnostics = Table(
    "analysis_diagnostics",
    metadata,
    Column(
        "snapshot_id",
        ForeignKey("analysis_snapshots.snapshot_id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("position", Integer, primary_key=True),
    Column("code", String, nullable=False),
    Column("message", String, nullable=False),
)
baselines = Table(
    "analysis_baselines",
    metadata,
    Column("recipe_id", String, primary_key=True),
    Column("recipe_version", String, primary_key=True),
    Column("analysis_id", ForeignKey("analyses.analysis_id"), nullable=False, unique=True),
)
